/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.HospitalAdminRole;


import Busines.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pharmaceutical_Manufacturer.MasterOrderCatalog;
import Business.Pharmaceutical_Manufacturer.Order;
import Business.Pharmaceutical_Manufacturer.OrderItem;
import Business.Pharmaceutical_Manufacturer.Product;
import Business.Pharmaceutical_Manufacturer.Supplier;
import Business.Pharmaceutical_Manufacturer.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.security.auth.login.AccountException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.ietf.jgss.Oid;
import userinterface.PharmaceuticalManufacturer.Purchase.PurchaseJPanel;
import userinterface.PharmaceuticalManufacturer.Purchase.ViewOrderItemDetailJPanel;

/**
 *
 * @author Jiaqi Wang
 * @author PeiLingChiang
 */
public class DrugManagementJPanel extends javax.swing.JPanel {


    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    List<Product> totalStock =new ArrayList<>();  
    /**
     * Creates new form DrugManagement
     */
    public DrugManagementJPanel(JPanel userprocesscontainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.userProcessContainer = userprocesscontainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
//     this.drugDirectory=drugDirectory;

   //不同批次的oder可能买入同种商品，这里用map归纳数量
        Map<Product, Integer> map = new HashMap<>();
        for (Order o : this.system.getMoc().getOrderCatalog()) {
            for (OrderItem oi : o.getOrderItemList()) {
                map.put(oi.getProduct(), oi.getQuantity());
            }
        }
        for (Product p : map.keySet()) {
            p.setInstock(map.get(p));
            totalStock.add(p);
        }
     

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productJTable = new javax.swing.JTable();

        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtprodName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        jLabel1.setText("Drug Management");

        productJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product's Name", "Usage", "Current Quantity in Stock"

            }
        ));
        jScrollPane1.setViewportView(productJTable);


        btnRemove.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnRemove.setText("Remove Item");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("微软雅黑", 2, 14)); // NOI18N
        jLabel3.setText("Please enter product's name:");

        btnSearch.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });


        backJButton.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addComponent(backJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 540, Short.MAX_VALUE)
                        .addComponent(btnRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 164, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprodName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)

                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(backJButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int row = productJTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product p = (Product) productJTable.getValueAt(row, 0);

        totalStock.remove(p);


        populateTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        String productName = txtprodName.getText();
        refreshProductTable(productName);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productJTable;
    private javax.swing.JTextField txtprodName;
    // End of variables declaration//GEN-END:variables

    private void refreshProductTable(String productName) {

        //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model = (DefaultTableModel) productJTable.getModel();
        model.setRowCount(0);
        for (Product p : totalStock) {

            if (p.getProdName().equalsIgnoreCase(productName)) {
                Object row[] = new Object[3];
                row[0] = p;
                row[1] = p.getProdUsage();
                row[2] = p.getInstock();
                model.addRow(row);

            }
        }
    }

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) productJTable.getModel();
        model.setRowCount(0);

        for (Product p : totalStock) {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getProdUsage();
            row[2] = p.getInstock();
            model.addRow(row);
        }

    }



    
}
