/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.HospitalAdminRole;

import Busines.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BP_PaymentSetltlementRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiaqi Wang
 */
public class FinanceManagementJPanel extends javax.swing.JPanel {
private JPanel upc;
private UserAccount account;
private Organization organization;
private Enterprise enterprise;


    /**
     * Creates new form FinanceManagementJPanel
     */
    public FinanceManagementJPanel(JPanel upc, UserAccount account,Organization organization ,Enterprise enterprise) {
        initComponents();
        this.upc=upc;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        populateTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();


        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel1.setText("Pending Bill List");

        billJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Date", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(billJTable);

        jButton1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton1.setText("Pay the bill now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });


        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(backJButton2))

                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(backJButton2))

        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = billJTable.getSelectedRow();
        WorkRequest wr = (WorkRequest)billJTable.getValueAt(selectedRow, 1);
        if (selectedRow<0){
            JOptionPane.showMessageDialog(null, "Your Selection is null,Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (wr.getStatus().equals("payment successful")){
            JOptionPane.showMessageDialog(null, "You has already paied the bill,Do not pay twice!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
            wr.setReceiver(account);
            wr.setStatus("payment successful");
        }
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify                     
    private javax.swing.JButton backJButton2;

    private javax.swing.JTable billJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   

    private void populateTable() {
      //To change body of generated methods, choose Tools | Templates.
       DefaultTableModel model = (DefaultTableModel)billJTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            if (request instanceof BP_PaymentSetltlementRequest){
                Object[] row = new Object[4];
                row[0] = request.getRequestDate();
                row[2] = request.getReceiver() == null ? null : request.getReceiver();
                row[1] = request;
                row[3] = request.getStatus();
                model.addRow(row);
            }
    }
        billJTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        billJTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        billJTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);  
}}
