/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.HospitalAdminRole;

import Business.Hospital.Ward;
import Business.Hospital.WardDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiaqi Wang
 * @author PeiLingChiang
 */
public class WardManagementJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private WardDirectory wardDirectory;
    private Ward ward;
    
    /**
     * Creates new form WardManagementJPanel
     */


    WardManagementJPanel(JPanel userprocesscontainer, WardDirectory wardDirectory) {
        initComponents();
        this.userProcessContainer = userprocesscontainer;
        this.wardDirectory = wardDirectory;
        
        populateTable();
        txtID.setEnabled(false);
        txtDep.setEnabled(false);
        txtCap.setEnabled(false);
        txtRemain.setEnabled(false);
        btnSubmit.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)wardJTable.getModel();
        model.setRowCount(0);  
        for(Ward w : wardDirectory.getWardList()){
            Object row[] = new Object[4];
            row[0] = w;
            row[1] = w.getDepartment();
            row[2] = w.getCapacity(); 
            row[3] = w.getRemainingBeds();
            model.addRow(row);
        }
    }

    private void refreshTable(int wardID) {
        DefaultTableModel model = (DefaultTableModel)wardJTable.getModel();
        model.setRowCount(0);
        for(Ward w : wardDirectory.getWardList()){
            if(w.getWardID() == wardID){
                Object row[] = new Object[4];
                row[0] = w;
                row[1] = w.getDepartment();
                row[2] = w.getCapacity(); 
                row[3] = w.getRemainingBeds();                   
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wardJTable = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtWardID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDep = new javax.swing.JTextField();
        txtCap = new javax.swing.JTextField();
        txtRemain = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        backJButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Ward Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 0, 252, 33));

        wardJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ward ID", "Department", "Capacity", "Remaining Beds"
            }
        ));
        jScrollPane1.setViewportView(wardJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 117, 462, 208));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 340, 90, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, -1));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 100, -1));

        jLabel2.setText("Please enter  Ward ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 87, -1, -1));
        add(txtWardID, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 82, 94, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 82, -1, -1));

        jLabel3.setText("Ward ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 127, -1, -1));

        jLabel4.setText("Department");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 165, -1, -1));

        jLabel5.setText("Remaining Beds");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 241, -1, -1));

        jLabel6.setText("Capacity");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 203, -1, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 122, 104, -1));
        add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 160, 104, -1));
        add(txtCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 198, 104, -1));
        add(txtRemain, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 236, 104, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 280, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 280, -1, -1));

        backJButton3.setText("<< Back");
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here: addSupplierJPanel asJP = new addSupplierJPanel(userProcessContainer, system.getSupplierDirectory());
        txtID.setText("");
        txtDep.setText("");
        txtCap.setText("");
        txtRemain.setText("");
        btnSubmit.setEnabled(true);
        txtID.setEnabled(true);
        txtDep.setEnabled(true);
        txtCap.setEnabled(true);
        txtRemain.setEnabled(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = wardJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ward = (Ward)wardJTable.getValueAt(row, 0);
        txtID.setText(String.valueOf(ward.getWardID()));
        txtDep.setText(ward.getDepartment());
        txtCap.setText(String.valueOf(ward.getCapacity()));
        txtRemain.setText(String.valueOf(ward.getRemainingBeds()));
        
        btnUpdate.setEnabled(true);
        txtDep.setEnabled(true);
        txtCap.setEnabled(true);
        txtRemain.setEnabled(true);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int row =wardJTable.getSelectedRow();

        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Ward w =(Ward)wardJTable.getValueAt(row, 0);
        wardDirectory.getWardList().remove(w);
        populateTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            int wardID = Integer.parseInt(txtWardID.getText());
            refreshTable(wardID);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numbers!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtCap.getText().length()==0 || txtRemain.getText().length()==0 
            || txtDep.getText().length()==0 || txtID.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            int ID = Integer.parseInt(txtID.getText());
            int cap = Integer.parseInt(txtCap.getText());
            int remain = Integer.parseInt(txtRemain.getText());
            String dep = txtDep.getText();
            
            Ward w = wardDirectory.addWard();
            w.setDepartment(dep);
            w.setCapacity(cap);
            w.setRemainingBeds(remain);
            w.setWardID(ID);
            
            txtID.setEnabled(false);
            txtDep.setEnabled(false);
            txtCap.setEnabled(false);
            txtRemain.setEnabled(false);
            btnSubmit.setEnabled(false);
            btnUpdate.setEnabled(false);
            populateTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for ID, Capacity and Remaining Beds!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtCap.getText().length()==0 || txtRemain.getText().length()==0 || txtDep.getText().length()==0 )
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            int cap = Integer.parseInt(txtCap.getText());
            int remain = Integer.parseInt(txtRemain.getText());
            String dep = txtDep.getText();
            
            ward.setDepartment(dep);
            ward.setCapacity(cap);
            ward.setRemainingBeds(remain);
            
            txtID.setEnabled(false);
            txtDep.setEnabled(false);
            txtCap.setEnabled(false);
            txtRemain.setEnabled(false);
            btnSubmit.setEnabled(false);
            btnUpdate.setEnabled(false);
            populateTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for Capacity and Remaining Beds!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton backJButton3;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRemain;
    private javax.swing.JTextField txtWardID;
    private javax.swing.JTable wardJTable;
    // End of variables declaration//GEN-END:variables

    
}
