/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.DoctorRole;

import Busines.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Doctor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Jiaqi Wang
 * @author PeiLingChiang
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel upc;
    private UserAccount account;
    private Organization organization;
//    private Enterprise enterprise;
    private EcoSystem system;
    private Doctor doctor;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */

    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem system) {

        initComponents();
        this.upc=userProcessContainer;
        this.account=account;
        this.organization=organization;
//        this.enterprise=enterprise;
        this.system=system;
        doctor = (Doctor)account.getPerson();

        ImageIcon ii=new ImageIcon("src/images/info.png");
        ii.setImage(ii.getImage().getScaledInstance(100,100 ,Image.SCALE_DEFAULT ));
//        (width, height,Image.SCALE_DEFAULT )
        lblPerson.setSize(100, 100);
        lblPerson.setIcon(ii);


        ImageIcon ii1=new ImageIcon("src/images/im_patient.png");
        ii1.setImage(ii1.getImage().getScaledInstance(120,120 ,Image.SCALE_DEFAULT ));

//        (width, height,Image.SCALE_DEFAULT )
        lblPatient.setSize(120, 120);
        lblPatient.setIcon(ii1);
//        lblPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Personal Info.jpg")));
//        lblPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Patient.jpg")));

        lblName.setText(doctor.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPerson = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblPatient = new javax.swing.JLabel();
        btnManage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lblPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 138, 110, 140));

        btnView.setText("View Personal Information");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 148, 100, 130));

        btnManage.setText("Manage Patients ");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 202, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Welcome, Doctor:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 221, 40));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblName.setText("(name)");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 105, 40));

        jButton1.setText("Accept New Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewPersonalINFO_JPanel vpiJP = new ViewPersonalINFO_JPanel(upc, doctor);
        upc.add("ViewPersonalINFO_JPanel", vpiJP);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        PatientManagementJPanel pmJP = new PatientManagementJPanel(upc, account, organization, system, doctor);
        upc.add("PatientManagement", pmJP);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_btnManageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AcceptPatientJPanel pmJP = new AcceptPatientJPanel(upc, account, organization, system, doctor);
        upc.add("AcceptPatientJPanel", pmJP);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPerson;
    // End of variables declaration//GEN-END:variables
}
