/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.DoctorRole;

import Business.University.Student;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Jiaqi Wang
 */
public class ViewPatientJPanel extends javax.swing.JPanel {
private JPanel upc;
private Student student;
    /**
     * Creates new form ViewPatientJPanel
     */
    public ViewPatientJPanel(JPanel upc, Student student) {
        initComponents();
        this.upc = upc;
        this.student = student;
        
        txtAge.setText(String.valueOf(student.getAge()));
        txtBlood.setText(student.getBloodtype());
        txtGender.setText(student.getGender());
        txtHeight.setText(student.getHeight());
        txtName.setText(student.getName());
        txtWeight.setText(String.valueOf(student.getWeight()));
        if (student.isPregant()) txtPregnancy.setText("Yes");
        else txtPregnancy.setText("No");
        txtEmName.setText(student.getEmergencyContactName());
        txtEmPhone.setText(String.valueOf(student.getEmergencyContactPhone()));
        txaAdverse.setText(student.getAdverseReactions());
        txaMedical.setText(student.getMedicalHistory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAdverse = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMedical = new javax.swing.JTextArea();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtBlood = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtPregnancy = new javax.swing.JTextField();
        txtEmName = new javax.swing.JTextField();
        txtEmPhone = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel4.setText("Gender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 118, 126, 30));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 154, 126, 30));

        jLabel6.setText("Blood Type:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 190, 126, 30));

        jLabel3.setText("Patient's Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 82, 126, 30));

        txtName.setEditable(false);
        txtName.setMinimumSize(new java.awt.Dimension(10, 20));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 82, 104, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("View Patient Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 0, 245, -1));

        jLabel9.setText("Pregnancy:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 306, -1, -1));

        jLabel10.setText("Emergency Contact Phone:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 124, -1, -1));

        jLabel11.setText("Medical History");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 169, -1, -1));

        jLabel12.setText("Adverse Reactions");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 169, -1, -1));

        jLabel13.setText("Emergency Contact Name:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 89, -1, -1));

        jLabel2.setText("Height:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 233, -1, -1));

        jLabel14.setText("Weight:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 270, -1, -1));

        txaAdverse.setEditable(false);
        txaAdverse.setColumns(20);
        txaAdverse.setRows(5);
        jScrollPane1.setViewportView(txaAdverse);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 203, 173, -1));

        txaMedical.setEditable(false);
        txaMedical.setColumns(20);
        txaMedical.setRows(5);
        jScrollPane2.setViewportView(txaMedical);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 203, 173, -1));

        txtGender.setEditable(false);
        txtGender.setMinimumSize(new java.awt.Dimension(10, 20));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 118, 104, 30));

        txtAge.setEditable(false);
        txtAge.setMinimumSize(new java.awt.Dimension(10, 20));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 154, 104, 30));

        txtBlood.setEditable(false);
        txtBlood.setMinimumSize(new java.awt.Dimension(10, 20));
        txtBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodActionPerformed(evt);
            }
        });
        add(txtBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 190, 104, 30));

        txtHeight.setEditable(false);
        txtHeight.setMinimumSize(new java.awt.Dimension(10, 20));
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 226, 104, 30));

        txtWeight.setEditable(false);
        txtWeight.setMinimumSize(new java.awt.Dimension(10, 20));
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 263, 104, 30));

        txtPregnancy.setEditable(false);
        txtPregnancy.setMinimumSize(new java.awt.Dimension(10, 20));
        txtPregnancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregnancyActionPerformed(evt);
            }
        });
        add(txtPregnancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 299, 104, 30));

        txtEmName.setEditable(false);
        txtEmName.setMinimumSize(new java.awt.Dimension(10, 20));
        txtEmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmNameActionPerformed(evt);
            }
        });
        add(txtEmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 82, 104, 30));

        txtEmPhone.setEditable(false);
        txtEmPhone.setMinimumSize(new java.awt.Dimension(10, 20));
        txtEmPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmPhoneActionPerformed(evt);
            }
        });
        add(txtEmPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 117, 104, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /**
        upc.remove(this);
        Component[] commponentArray = upc.getComponents();
        Component component = commponentArray[commponentArray.length-1];
        PatientManagementJPanel pmjp = (PatientManagementJPanel) component;
        pmjp.populateRegisteredTable();
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
        **/
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtPregnancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregnancyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregnancyActionPerformed

    private void txtEmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmNameActionPerformed

    private void txtEmPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmPhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txaAdverse;
    private javax.swing.JTextArea txaMedical;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtEmName;
    private javax.swing.JTextField txtEmPhone;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPregnancy;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
