/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.DoctorRole;

import Business.Hospital.Doctor;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 * @author PeiLingChiang
 */
public class ViewPersonalINFO_JPanel extends javax.swing.JPanel {
    
    private JPanel upc;
    private Doctor doctor;
    
    /**
     * Creates new form ViewDoctorJPanel
     */
  
    ViewPersonalINFO_JPanel(JPanel userProcessContainer, Doctor d) {
        initComponents();
        this.upc = userProcessContainer;
        this.doctor = d;
        txtName.setText(doctor.getName());
        txtID.setText(String.valueOf(doctor.getId()));
        txtDepartment.setText(doctor.getDepartment());
        txtJobTitile.setText(doctor.getJobTitle());
        
        txtName.setEnabled(false);
        txtID.setEnabled(false);
        txtDepartment.setEnabled(false);
        txtJobTitile.setEnabled(false);
        btnSave.setEnabled(false);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtJobTitile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 172, 183, 32));
        add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 210, 183, 32));
        add(txtJobTitile, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 248, 183, 32));

        jLabel2.setText("Doctor's Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 134, 130, 32));

        jLabel3.setText("Doctor's ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 172, 130, 32));

        jLabel4.setText("Department:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 210, 130, 32));

        jLabel5.setText("Job Title:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 248, 130, 32));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 134, 183, 32));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("View Doctor Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 0, 292, 37));

        btnUpdate.setForeground(new java.awt.Color(0, 51, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 307, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, -1, -1));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 306, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        txtName.setEnabled(true);
        txtDepartment.setEnabled(true);
        txtJobTitile.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtName.getText().length()==0 || txtDepartment.getText().length()==0 || txtJobTitile.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        doctor.setName(txtName.getText());
        doctor.setDepartment(txtDepartment.getText());
        doctor.setJobTitle(txtJobTitile.getText());
        
        JOptionPane.showMessageDialog(null, "Successfully updated!");
        txtName.setEnabled(false);
        txtDepartment.setEnabled(false);
        txtJobTitile.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJobTitile;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
