/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UniversityAdminRole;

import Busines.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.Role.StudentRole;
import Business.University.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeiLingChiang
 */
public class ManageStudentsJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Organization studentOrg;
    Enterprise enterprise;
    EcoSystem business;
    Student s;
    UserAccount ua;
    
    /**
     * Creates new form ManageStudentsJPanel
     */
    public ManageStudentsJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        
        //get student org
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (o instanceof StudentOrganization){
                studentOrg = o;
            }
        }
        
        populateTable();
        btnUpdate.setEnabled(false);
        btnCreate.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        txtName.setEnabled(false);
        txtClassroomID.setEnabled(false);
        txtStudentID.setEnabled(false);
        txtAge.setEnabled(false);        
        txtPhone.setEnabled(false);        
        txtAddress.setEnabled(false);        
        txtState.setEnabled(false);        
        txtZip.setEnabled(false);
        txtGender.setEnabled(false);      
        txtCountry.setEnabled(false);
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        for (UserAccount ua : studentOrg.getUserAccountDirectory().getUserAccountList()){
            Object[] row = new Object[2];
            row[0] = ua.getPerson();
            row[1] = ua;
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtClassroomID = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCreateNew = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 31, 264, 310));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 100, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 73, 97, -1));

        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 78, -1, -1));

        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 110, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 105, 97, -1));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 142, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 137, 97, -1));

        jLabel4.setText("Student ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 174, -1, -1));
        add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 169, 97, -1));

        jLabel16.setText("Gender:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        jLabel18.setText("Age:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 206, -1, -1));

        jLabel11.setText("Country of Citizenship:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        jLabel7.setText("Phone Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 142, -1, -1));

        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 174, -1, -1));

        jLabel9.setText("State:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 206, -1, -1));

        jLabel10.setText("Zip Code:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 238, -1, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 201, 97, -1));
        add(txtClassroomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 233, 97, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 73, 97, -1));

        jLabel12.setText("Classroom ID:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 238, -1, -1));
        add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 105, 97, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 137, 97, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 169, 97, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 201, 97, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 233, 97, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        btnCreateNew.setText("Create New");
        btnCreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewActionPerformed(evt);
            }
        });
        add(btnCreateNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            s = (Student)tblStudents.getValueAt(selectedRow, 0);
            ua = (UserAccount) tblStudents.getValueAt(selectedRow, 1);
            
            txtName.setText(s.getName());
            txtUsername.setText(ua.getUsername());
            txtPassword.setText(ua.getPassword());
            txtStudentID.setText(Integer.toString(s.getId()));
            txtAge.setText(Integer.toString(s.getAge()));
            txtClassroomID.setText(Integer.toString(s.getClassroomID()));
            txtGender.setText(s.getGender());
            txtCountry.setText(s.getCountry_of_citizenship());
            txtPhone.setText(Integer.toString(s.getPhoneNumber()));
            txtAddress.setText(s.getAddress());
            txtState.setText(s.getState());
            txtZip.setText(s.getZipcode());
            
            btnUpdate.setEnabled(true);
            btnCreate.setEnabled(false);
            txtUsername.setEnabled(false);
            txtPassword.setEnabled(true);
            txtName.setEnabled(true);
            txtClassroomID.setEnabled(true);
            txtStudentID.setEnabled(false);
            txtAge.setEnabled(true);        
            txtPhone.setEnabled(true);        
            txtAddress.setEnabled(true);        
            txtState.setEnabled(true);        
            txtZip.setEnabled(true);
            txtGender.setEnabled(true);      
            txtCountry.setEnabled(true);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().length()==0 || txtName.getText().length()==0 || txtCountry.getText().length()==0 || 
            txtClassroomID.getText().length()==0 || txtAge.getText().length()==0 || txtGender.getText().length()==0 || 
            txtPhone.getText().length()==0 || txtAddress.getText().length()==0 || txtState.getText().length()==0 || 
            txtZip.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            Integer.parseInt(txtAge.getText());
            Integer.parseInt(txtPhone.getText());
            Integer.parseInt(txtClassroomID.getText());
            
            ua.setPassword(txtPassword.getText());
            s.setName(txtName.getText());
            s.setClassroomID(Integer.parseInt(txtClassroomID.getText()));
            s.setAge(Integer.parseInt(txtAge.getText()));
            s.setPhoneNumber(Integer.parseInt(txtPhone.getText()));
            s.setAddress(txtAddress.getText());
            s.setState(txtState.getText());
            s.setZipcode(txtZip.getText());
            s.setGender(txtGender.getText());
            s.setCountry_of_citizenship(txtCountry.getText());
            
            btnUpdate.setEnabled(false);
            btnCreate.setEnabled(false);
            txtUsername.setEnabled(false);
            txtPassword.setEnabled(false);
            txtName.setEnabled(false);
            txtClassroomID.setEnabled(false);
            txtStudentID.setEnabled(false);
            txtAge.setEnabled(false);        
            txtPhone.setEnabled(false);        
            txtAddress.setEnabled(false);        
            txtState.setEnabled(false);        
            txtZip.setEnabled(false);
            txtGender.setEnabled(false);      
            txtCountry.setEnabled(false);
            populateTable();
            JOptionPane.showMessageDialog(null, "Successfully updated!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for Age, Phone Number and Classroon ID!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().length()==0 || txtName.getText().length()==0 || txtCountry.getText().length()==0 || 
            txtClassroomID.getText().length()==0 || txtAge.getText().length()==0 || txtGender.getText().length()==0 || 
            txtPhone.getText().length()==0 || txtAddress.getText().length()==0 || txtState.getText().length()==0 || 
            txtZip.getText().length()==0 || txtUsername.getText().length()==0) 
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (studentOrg.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())==false){
            JOptionPane.showMessageDialog(null, "The username has existed!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            Integer.parseInt(txtAge.getText());
            Integer.parseInt(txtPhone.getText());
            Integer.parseInt(txtClassroomID.getText());
            
            Student student = studentOrg.getPersonDirectory().createStudent
                    (txtName.getText(), Integer.parseInt(txtPhone.getText()), txtAddress.getText(), 
                    txtState.getText(), txtZip.getText(), txtGender.getText(), Integer.parseInt(txtAge.getText()), 
                    txtCountry.getText(), Integer.parseInt(txtClassroomID.getText()));
            business.getStudentDir().getStudentList().add(student);
            studentOrg.getUserAccountDirectory().createUserAccount(txtUsername.getText(), txtPassword.getText(), student, new StudentRole());
            
            /**
            //testing
            student.setTestingStatus("positive");
            student.setContactStatus("quarantine");
            student.setQuarantineStartDate(LocalDate.now().minusDays(1));
            **/
            
            btnUpdate.setEnabled(false);
            btnCreate.setEnabled(false);
            txtUsername.setEnabled(false);
            txtPassword.setEnabled(false);
            txtName.setEnabled(false);
            txtClassroomID.setEnabled(false);
            txtStudentID.setEnabled(false);
            txtAge.setEnabled(false);        
            txtPhone.setEnabled(false);        
            txtAddress.setEnabled(false);        
            txtState.setEnabled(false);        
            txtZip.setEnabled(false);
            txtGender.setEnabled(false);      
            txtCountry.setEnabled(false);
            txtStudentID.setText(Integer.toString(student.getId()));
            populateTable();
            JOptionPane.showMessageDialog(null, "Successfully created!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for Age, Phone Number and Classroon ID!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewActionPerformed
        // TODO add your handling code here:
        btnCreate.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        txtName.setEnabled(true);
        txtClassroomID.setEnabled(true);
        txtStudentID.setEnabled(false);
        txtAge.setEnabled(true);        
        txtPhone.setEnabled(true);        
        txtAddress.setEnabled(true);        
        txtState.setEnabled(true);        
        txtZip.setEnabled(true);
        txtGender.setEnabled(true);      
        txtCountry.setEnabled(true);
        
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtStudentID.setText("");
        txtAge.setText("");
        txtClassroomID.setText("");
        txtGender.setText("");
        txtCountry.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtState.setText("");
        txtZip.setText("");
    }//GEN-LAST:event_btnCreateNewActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtClassroomID;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
