/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Busines.EcoSystem;
import Business.University.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PeiLingChiang
 */
public class RegistrationJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem business;
    Student student;
    
    /**
     * Creates new form RegistrationJPanel
     */
    public RegistrationJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.student = student;
        
        if (student.getHeight()!=null){

            txtHeight.setText(student.getHeight());
            txtWeight.setText(String.valueOf(student.getWeight()));
            txtBlood.setText(student.getBloodtype());
            if (student.isPregant()== true) rbYes.setSelected(true);
            else rbNo.setSelected(true);
            txtEPhone.setText(String.valueOf(student.getEmergencyContactPhone()));
            txtEName.setText(student.getEmergencyContactName());
            txaMedical.setText(student.getMedicalHistory());
            txaAdverse.setText(student.getAdverseReactions());
            btnSubmit.setEnabled(false);
            btnFind.setEnabled(true);
            txtHeight.setEnabled(false);
            txtWeight.setEnabled(false);
            txtBlood.setEnabled(false);
            rbYes.setEnabled(false);
            rbNo.setEnabled(false);
            txtEPhone.setEnabled(false);
            txtEName.setEnabled(false);
            txaMedical.setEnabled(false);
            txaAdverse.setEnabled(false);
        }
        else {
            btnSubmit.setEnabled(true);
            btnFind.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        backJButton = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBlood = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtEPhone = new javax.swing.JTextField();
        txtEName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAdverse = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMedical = new javax.swing.JTextArea();
        btnFind = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 476, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 382, 100, -1));

        jLabel3.setText("Blood Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 188, -1, -1));

        jLabel4.setText("Pregnant");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 215, -1, -1));

        jLabel5.setText("Emergency Contact Phone");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 311, -1, -1));

        jLabel6.setText("Medical History");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 119, -1, -1));

        jLabel7.setText("Adverse Reactions");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 235, -1, -1));

        jLabel11.setText("Emergency Contact Name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 279, -1, -1));
        add(txtBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 183, 100, -1));
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 151, 100, -1));
        add(txtEPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 311, 100, -1));
        add(txtEName, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 279, 100, -1));

        jLabel1.setText("Height");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 119, -1, -1));
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 119, 100, -1));

        jLabel2.setText("Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 156, -1, -1));

        buttonGroup.add(rbYes);
        rbYes.setText("Yes");
        add(rbYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 215, -1, -1));

        buttonGroup.add(rbNo);
        rbNo.setText("No");
        add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 244, -1, -1));

        txaAdverse.setColumns(20);
        txaAdverse.setRows(5);
        jScrollPane1.setViewportView(txaAdverse);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 257, 173, -1));

        txaMedical.setColumns(20);
        txaMedical.setRows(5);
        jScrollPane2.setViewportView(txaMedical);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 141, 173, 76));

        btnFind.setText("Find Doctor >>");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 382, 123, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtHeight.getText().length()==0 || txtWeight.getText().length()==0 ||txtBlood.getText().length()==0 || 
            txtEPhone.getText().length()==0 || txtEName.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!rbYes.isSelected() && !rbNo.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select Yes or No for pregnancy!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try{
            Integer.parseInt(txtEPhone.getText());
            Double.parseDouble(txtWeight.getText());

            student.setHeight(txtHeight.getText());
            student.setWeight(Double.parseDouble(txtWeight.getText()));
            student.setBloodtype(txtBlood.getText());
            student.setEmergencyContactPhone(Integer.parseInt(txtEPhone.getText()));
            student.setEmergencyContactName(txtEName.getText());
            student.setMedicalHistory(txaMedical.getText());
            student.setAdverseReactions(txaAdverse.getText());
            if (rbYes.isSelected()){
                student.setPregant(true);
            }
            else
                student.setPregant(false);
            
            JOptionPane.showMessageDialog(null, "Successfully registered!");

            txtWeight.setEnabled(false);
            txtHeight.setEnabled(false);
            txtBlood.setEnabled(false);
            txtEPhone.setEnabled(false);
            txtEName.setEnabled(false);
            txaMedical.setEnabled(false);
            txaAdverse.setEnabled(false);
            btnSubmit.setEnabled(false);
            btnFind.setEnabled(true);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for Emergency Contact Phone and Weight!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("PatientWorkArea", new PatientWorkAreaJPanel(userProcessContainer, account, business, student));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JTextArea txaAdverse;
    private javax.swing.JTextArea txaMedical;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEPhone;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
