/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.University.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PeiLingChiang
 */
public class ViewAccountJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    UserAccount account;
    Student student;
    
    /**
     * Creates new form ViewAccountJPanel
     */
    public ViewAccountJPanel(JPanel userProcessContainer, UserAccount account, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.student = student;
        
        txtUsername.setText(account.getUsername());
        txtPassword.setText(account.getPassword());
        txtName.setText(student.getName());
        txtID.setText(Integer.toString(student.getId()));
        txtAge.setText(Integer.toString(student.getAge()));
        txtGender.setText(student.getGender());
        txtCountry.setText(student.getCountry_of_citizenship());
        txtPhone.setText(Integer.toString(student.getPhoneNumber()));
        txtAddress.setText(student.getAddress());
        txtState.setText(student.getState());
        txtZip.setText(student.getZipcode());
        
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        txtName.setEnabled(false);
        txtID.setEnabled(false);
        txtAge.setEnabled(false);    
        txtGender.setEnabled(false);      
        txtCountry.setEnabled(false);        
        txtPhone.setEnabled(false);        
        txtAddress.setEnabled(false);        
        txtState.setEnabled(false);        
        txtZip.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSubmit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 109, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 109, 120, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 146, -1, -1));

        jLabel3.setText("StudentID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 178, -1, -1));

        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel5.setText("Phone Number");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, 10));

        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, 10));

        jLabel7.setText("State");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, 10));

        jLabel8.setText("Zip Code");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, 10));

        jLabel11.setText("Country of Citizenship");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel16.setText("Gender");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 274, -1, -1));

        jLabel18.setText("Age");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 242, -1, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 173, 120, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 141, 120, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 205, 120, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 237, 120, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 146, 110, -1));
        add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 114, 110, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 178, 110, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 210, 110, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 242, 110, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 274, 120, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 344, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 344, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 344, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtPassword.setEnabled(true);
        txtName.setEnabled(true);
        txtAge.setEnabled(true);  
        txtGender.setEnabled(true);      
        txtCountry.setEnabled(true);
        txtPhone.setEnabled(true);        
        txtAddress.setEnabled(true);        
        txtState.setEnabled(true);        
        txtZip.setEnabled(true);
        btnSubmit.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().length()==0 || txtName.getText().length()==0 || txtCountry.getText().length()==0 || 
            txtAge.getText().length()==0 || txtGender.getText().length()==0 || txtPhone.getText().length()==0 || 
            txtAddress.getText().length()==0 || txtState.getText().length()==0 || txtZip.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Please ensure all fields are entered!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            Integer.parseInt(txtAge.getText());
            Integer.parseInt(txtPhone.getText());
            
            account.setPassword(txtPassword.getText());
            student.setName(txtName.getText());
            student.setAge(Integer.parseInt(txtAge.getText()));
            student.setPhoneNumber(Integer.parseInt(txtPhone.getText()));
            student.setAddress(txtAddress.getText());
            student.setState(txtState.getText());
            student.setZipcode(txtZip.getText());
            student.setGender(txtGender.getText());
            student.setCountry_of_citizenship(txtCountry.getText());
            JOptionPane.showMessageDialog(null, "Successfully updated!");
            
            txtPassword.setEnabled(false);
            txtName.setEnabled(false);
            txtAge.setEnabled(false);        
            txtPhone.setEnabled(false);        
            txtAddress.setEnabled(false);        
            txtState.setEnabled(false);        
            txtZip.setEnabled(false);
            txtGender.setEnabled(false);      
            txtCountry.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnSubmit.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter only numbers for Age and Phone Number!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
